src/Swarminfo/ImagescriptBundle/Entity/Project.php
<?php

namespace Swarminfo\ImagescriptBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Project
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Swarminfo\ImagescriptBundle\Entity\ProjectRepository")
 */
class Project
{

    private $premiumText = "Please login as premium login"; 
    
    public function __construct(){
        //empty json by default
	$this->data = "{}";
    } 


    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="bigint")
     * @ORM\Id
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="data", type="text")
     */
    private $data;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    
    /**
     * Set id
     *
     * @param string $id
     *
     * @return Project
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }
    
    
    /**
     * Set data
     *
     * @param string $data
     *
     * @return Project
     */
    public function setData($data)
    {
        $this->data = $data;

        return $this;
    }
    
    /**
     * Get data
     *
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }
    
    //same as get data but replace the legends by "subscribe to premium"
    public function getLimitedData(){
	$data = json_decode($this->getData(),true);
	foreach($data["legends"] as $lid => $ldata){
	    foreach($ldata["text"] as $language=>$tdata){
		$data["legends"][$lid]["text"][$language] = $this->premiumText;
	    }
	    $data["legends"][$lid]["description"] = $this->premiumText;
	}
	return json_encode($data);
    }
    
    //check whether the project is free or not
    public function isFree(){
        $data = json_decode($this->getData(),true);
        return isset($data["general"]["free"]) && $data["general"]["free"] == "free";
    }

    //check whether the project is publish or not
    public function isPublish(){
        $data = json_decode($this->getData(),true);
        return isset($data["general"]["publish"]) && $data["general"]["publish"] == "publish";
    }

    //check whether the project in front page or not
    public function isOnfront(){
        $data = json_decode($this->getData(),true);
        return isset($data["general"]["onfrontpage"]) && $data["general"]["onfrontpage"] == "onfrontpage";
    }
    
    //get weight
    public function getweight(){
        $data = json_decode($this->getData(),true);
        if (is_null($data["general"]["weight"]))
            return 99999;
        return $data["general"]["weight"];
    }
    
}

src/Swarminfo/ImagescriptBundle/Resources/views/addregister_edit.html.twig
{% trans_default_domain 'FOSUserBundle' %}
<h4>{{ 'registration.accountdetails'|trans }}</h4>
<div>
    <label for="fos_user_registration_form_title" class="required">{{ 'registration.title'|trans }}</label>
    <select id="fos_user_registration_form_title" class="required" name="_title" >
        {% if fieldsreg %}
            {% for t in title %}
                <option value="{{ t }}"
                        {{ t==fieldsreg.getTitle ? ' selected ' }}
                >
                    {{ t }}</option>
            {% endfor %}
        {% else %}
            <option value=" "> </option>
            {% for t in title %}
                <option value="{{ t }}"  >
                    {{ t }}</option>
            {% endfor %}
        {% endif %}
    </select>
</div>

<div>
    <label for="fos_user_registration_form_firstname" class="required">{{ 'registration.firstname'|trans }}</label>
    <input type="text" id="fos_user_registration_form_firstname" name="_firstname" required="required"
            {% if fieldsreg %}
           value={{ fieldsreg.getFirstname }}
           {% endif %}
    >
</div>

<div>
    <label for="fos_user_registration_form_lastname" class="required">{{ 'registration.lastname'|trans }}</label>
    <input type="text" id="fos_user_registration_form_lastname" name="_lastname" required="required"
        {% if fieldsreg %}
           value={{ fieldsreg.getLastname }}
        {% endif %}
    >
</div>

<div>
    <label for="fos_user_registration_form_profession" class="required">{{ 'registration.profession'|trans }}</label>
    <select id="fos_user_registration_form_profession" class="required" name="_profession">
        {% if fieldsreg %}
            {% for p in professions %}
                <option value="{{ p }}"
                        {{ p==fieldsreg.getProfession ? ' selected ' }}
                >
                    {{ p }}</option>
            {% endfor %}
        {% else %}
            <option value=" "> </option>
            {% for p in professions %}
                <option value="{{ p }}" >  {{ p }}</option>
            {% endfor %}
        {% endif %}
    </select>
</div>


<div>
    <label for="fos_user_registration_form_country" class="required">{{  'registration.country'|trans }}</label>
    <select id="fos_user_registration_form_country" name="_country" required="required">
        {% if fieldsreg %}
            {% for key,c in countries %}
                <option value="{{ key }}"
                        {{ key==fieldsreg.getCountry ? ' selected ' }}
                >
                    {{ c}}</option>
            {% endfor %}
        {% else %}
            <option value=" "> </option>
            {% for key,c in countries %}
                <option value="{{ key }}" >{{ c}}</option>
            {% endfor %}
        {% endif %}
    </select>
</div>

<div>
    <label for="fos_user_registration_form_addresline1">{{ 'registration.address1'|trans }}</label>
    <input type="text" id="fos_user_registration_form_addresline1" name="_addresline1"
        {% if fieldsreg %}
           value={{ fieldsreg.getAddressLine1 }}
        {% endif %}
    >
</div>

<div>
    <label for="fos_user_registration_form_addresline2">{{ 'registration.address2'|trans }}</label>
    <input type="text" id="fos_user_registration_form_addresline2" name="_addresline2"
        {% if fieldsreg %}
           value={{ fieldsreg.getAddressLine2 }}
        {% endif %}
    >
</div>

<div>
    <label for="fos_user_registration_form_city" class="required">{{ 'registration.city'|trans }}</label>
    <input type="text" id="fos_user_registration_form_city" name="_city"
        {% if fieldsreg %}
           value={{ fieldsreg.getCity }}
        {% endif %}
    >
</div>


<div>
    <label for="fos_user_registration_form_phone" >{{ 'registration.phone'|trans }}</label>
    <input type="text" id="fos_user_registration_form_phone" name="_phone" required="required"
            {% if fieldsreg %}
                 value={{ fieldsreg.getPhone }}
            {% endif %}>
</div>


<div>
    <label for="fos_user_registration_form_promo_code" >{{ 'registration.promocode'|trans }}</label>
    <input type="text" id="fos_user_registration_form_promo_code" name="_promo_code"
            {% if fieldsreg %}
    value={{ fieldsreg.getPromocode }}
            {% endif %}>
</div>

<div>
    <input type="checkbox" name="_receive1"
            {% if fieldsreg %}
                {{ fieldsreg.isComPref1==1 ? ' checked ' }}
            {% endif %}
    > {{ 'registration.iagreetoreseiveemail'|trans }}<br>
    <br>
</div>

src/Swarminfo/ImagescriptBundle/Resources/views/adminIframe.html.twig
{% extends "SwarminfoImagescriptBundle::iframe.html.twig" %}

{% block admin %}
    <div class=scriptDiv id=topadminpannel></div>
    <div class=scriptDiv id=mainadminpannel></div>
{% endblock %}                    

{% block scripts %}
    {{ parent() }}
    {{ parent() }}
    {# add javascript for the administration to edit the project #}
    {% javascripts
        '@SwarminfoImagescriptBundle/Resources/public/js/imagescriptadmin.js'
        '@SwarminfoImagescriptBundle/Resources/public/js/imagescriptadminimage.js'
        '@SwarminfoImagescriptBundle/Resources/public/js/imagescriptadminlegend.js'
        '@SwarminfoImagescriptBundle/Resources/public/js/imagescriptadminstructure.js'
        '@SwarminfoImagescriptBundle/Resources/public/js/imagescriptadminlanguage.js'
        '@SwarminfoImagescriptBundle/Resources/public/js/imagescriptadminseries.js'
        '@SwarminfoImagescriptBundle/Resources/public/js/imagescriptadmingeneral.js'
        '@SwarminfoImagescriptBundle/Resources/public/js/imagescripttrackdownadmin.js'
        '@SwarminfoImagescriptBundle/Resources/public/js/imagescriptlogadmin.js'
    %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
    
{% endblock %}

src/Swarminfo/ImagescriptBundle/Resources/views/admin_create_user.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}
{#{% block add_class %} class="logged-in profile-edit"{% endblock %}#}
{#{% block start_class %} <div class="logged-in profile-edit">{% endblock %}#}
    {#{% block end_class %} </div> {% endblock %}#}

{% block add_class %} class="logged-in admin_create_user"{% endblock %}

{% block fos_user_content %}
    <form action="{{ path('swarminfo_imagescript_create_user_from_admin', {}) }}" method="post">
        {#<h4>Create new User </h4>#}
        <h4>USER PROFILE<small>&nbsp;&nbsp;<b>*</b>&nbsp;&nbsp;Required fields</small></h4>
        {% if message!=NULL %}
            <ui>{{ message}}</ui>
                <br>
        {% endif %}

        {#username#}
        <label >Username</label>
        <input type="text" id="username" name="_username" required="required" /><td>
        {#email#}
        <label>Email </label>
        <input type="text" id="email" name="_email" required="required"/><td>
        {#password#}
        <label>Password </label>
        <input type="text" id="password" name="_userpass" placeholder="Enter password" required="required"/><td>
        <label>Repeat Password </label>
        <input type="text" id="repeat_password" name="_repeatuserpass" placeholder="Repeat Password" required="required"/><td>

        <h4>ACCOUNT DETAILS</h4>
            <div>
                <label for="fos_user_registration_form_title" >Title</label>
                <select id="fos_user_registration_form_title" name="_title" >
                        <option value=" "> </option>
                        {% for t in title %}
                            <option value="{{ t }}"  >
                                {{ t }}</option>
                        {% endfor %}
                </select>
            </div>

            <div>
                <label for="fos_user_registration_form_firstname" class="required">First name *</label>
                <input type="text" id="fos_user_registration_form_firstname" name="_firstname" required="required"/>
            </div>

            <div>
                <label for="fos_user_registration_form_lastname" class="required">Last Name *</label>
                <input type="text" id="fos_user_registration_form_lastname" name="_lastname"  required="required"/>
            </div>

            <div>
                <label for="fos_user_registration_form_profession" class="required">Profession *</label>
                <select id="fos_user_registration_form_profession" required="required" name="_profession">
                        <option value=" "> </option>
                        {% for p in professions %}
                            <option value="{{ p }}" >  {{ p }}</option>
                        {% endfor %}
                </select>
            </div>


            <div>
                <label for="fos_user_registration_form_country" class="required">Country *</label>
                <select id="fos_user_registration_form_country" name="_country" required="required">
                        <option value=" "> </option>
                        {% for key,c in countries %}
                            <option {{ key=='US' ? ' selected=selected ' }} value="{{ key }}"   >{{ c}}</option>
                        {% endfor %}
                </select>
            </div>

            <div>
                <label for="fos_user_registration_form_addresline1">Address line 1</label>
                <input type="text" id="fos_user_registration_form_addresline1" name="_addresline1"/>
            </div>

            <div>
                <label for="fos_user_registration_form_addresline2">Address line 2</label>
                <input type="text" id="fos_user_registration_form_addresline2" name="_addresline2" />
            </div>

            <div>
                <label for="fos_user_registration_form_city" >City/State</label>
                <input type="text" id="fos_user_registration_form_city" name="_city" />
            </div>

            <div>
                <label for="fos_user_registration_form_phone" >Phone number *</label>
                <input type="text" id="fos_user_registration_form_phone" required="required" name="_phone" />
            </div>

            <div>
                <input type="checkbox" name="_receive1"/> I agree to receive e-mails relating to OMCSA information, services and products.<br>
                <br>
            </div>


            <input type="submit" value="Create user">

    </form>

    <script>
        var password = document.getElementById("password")
        var confirm_password = document.getElementById("repeat_password");

        function validatePassword(){
            if(password.value != confirm_password.value) {
                confirm_password.setCustomValidity("Passwords Don't Match");
            }
            else {
                confirm_password.setCustomValidity('');
            }
        }

        password.onchange = validatePassword;
        repeat_password.onkeyup = validatePassword;
    </script>

{% endblock fos_user_content %}

src/Swarminfo/ImagescriptBundle/Resources/views/adminpannel.html (copy).twig
<section>
    <div class="container">
            <div class="row">
                    <div class="col-md-16 col-sm-12 text-left">
                            <h1 class="uppercase">admin pannel</h1><br/>
                            <a href='{{ path('swarminfo_imagescript_edit', {}) }}'> create a new project</a>
                            <div class="tabbed-content text-tabs">
                                    <ul class="tabs">
                                        {% for tag in projects|keys %}
                                            <li class="active">
                                                <div class="tab-title">
                                                        <span>{{tag}}</span>
                                                </div>
                                                <div class="tab-content">
                                                                
                                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                                <tr>
                                                                {% for pid in projects[tag]|keys %}
                                                                        <td width="25%" height="150px" valign="top" style="vertical-align:top;"><div class="e_title"><h6>{{projects[tag][pid].name}} <span class="color-red">Premium</span></h6></div><a href="{{ path('swarminfo_imagescript_edit', {}) }}?id={{projects[tag][pid].id}}"><img class="cast-shadow" alt="Screenshot" src="{{projects[tag][pid].url}}" width="85px"></a> {{projects[tag][pid].images}} Images</td>
                                                                    {% if (pid+1) is divisible by(4) %}
                                                                </tr>
                                                                <tr>
                                                                    {% endif %}
                                                                {% endfor %}
                                                                </tr>
                                                        </table>
                                                </div>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                            
                            </div>
                            
                    </div>
            </div>
            
    </div>
    
</section>

src/Swarminfo/ImagescriptBundle/Resources/views/core.html.twig
{% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
	Connected as {{ app.user.username }}
	-
	<a href="{{ path('fos_user_security_logout') }}">disconnect</a>
{% else %}
	<a href="{{ path('fos_user_security_login') }}">connect</a>
	<a href="{{ path('fos_user_registration_register') }}">register</a> 
{% endif %} 

{% block body %}
{% endblock %}

src/Swarminfo/ImagescriptBundle/Resources/views/footer.html.twig
<footer class="footer-2"> <!-- bg-dark -->
    <div class="container">
        <div class="row">

            <div class="col-sm-4">
							<span>
								© Copyright 2016 OMCSA - All Rights Reserved
							</span>
            </div>
        </div>
    </div>
</footer>

src/Swarminfo/ImagescriptBundle/Resources/views/page2.html.twig
{% extends "SwarminfoImagescriptBundle::skeleton.html.twig" %}
{% trans_default_domain 'FOSUserBundle' %}
{% block add_class %} class="{% if user!='anon.' %}logged-in {% endif %}anatomy front-page"{% endblock %}
{% block headinfo %}

    <script src="/js/jquery.min.js"></script>


    <![if !IE]>
    <link href="/css/page2.css" rel="stylesheet">
    <![endif]>

    <!--[if lt IE 10]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

    <link href="/css/page2_ie8.css" rel="stylesheet" type="text/css"/>

    <![endif]-->

    <!--[if gt IE 9]>
    <link href="/css/page2.css" rel="stylesheet">
    <script>
        var ie9 = true;
    </script>

    <![endif]-->

    <script src="/js/page2.js"></script>

    {#<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">#}
    {#<link rel="stylesheet" href="/resources/demos/style.css">#}



{% endblock %}

{% block body %}
    <div class="main-container">
<section>
    <div class="container">
            <div class="row">
                    <div class="col-md-16 col-sm-12 text-left">
                            <h2 class="uppercase">{{ 'mainpage.title1'|trans }}</h2>
							<span class="txtname">{{ 'mainpage.txtname'|trans }} </span> <span class="txtnametitle">{{ 'mainpage.txtnametitle'|trans }} </span><br/>
                            <h3>{{ 'mainpage.title2'|trans }}</h3>
                            <p>
                                    <b>{{ 'mainpage.welcome'|trans }}</b>
                            </p>
                            <p>
                                {{ 'mainpage.text1'|trans }}<br/>
                                {{ 'mainpage.text2'|trans }}
                            <!-- For accessing all the labellings and the complete module list, simply subscribe to a license. --><br/>
                            </p>
                            <div class="searchfiled">

                                {#<form action="{{ path('swarminfo_imagescript_page2', {}) }}" method="post">#}
                                    {#<input class="search" name="search" id="search_legend" type="text" placeholder="search anatomy"#}
                                    {#{% if search %}#}
                                        {#value="{{ search }}"#}
                                    {#{% endif %}#}
                                    {#>#}

                                    {#<div id="legendSearchDiv" style="z-index: 999; position: absolute;width:280px;height:500[x];max-height:300px;">#}
                                        {#<a href="#" class="legendSearchChoice" lid="FIRST">FIRST</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="Third">Third</a>#}
                                        {#<br></div>#}

                                    {#<input class="btnsearch" type="submit" value="Search">#}
                                {#</form>#}

                                <input class="search" name="search" id="search_legend" type="text" placeholder="search anatomy"
                                        {% if search %}
                                            value="{{ search }}"
                                        {% endif %}
                                >

                                <div id="clear-input">X</div>

                                <div id="legendSearchDiv" >
                                    {#<a href="#" class="legendSearchChoice" lid="FIRST">FIRST</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="second">second</a><br><a href="#" class="legendSearchChoice" lid="Third">Third</a>#}
                                    <br></div>

                            </div>
                            <div class="tabbed-content text-tabs" {% if search %} style="display: block" {% endif %}>
                                    <ul class="tabs">
                                        {% for tag in projects|keys%}
                                            {% if not search %}
                                                <li class="active">

                                                <div class="tab-title">
                                                        <span>
                                                            {% if tag=='head' %}
                                                                {{ 'mainpage.taghead'|trans }}
                                                            {% elseif tag=='TEST' %}
                                                                {{ 'mainpage.tagtest'|trans }}
                                                            {% elseif tag=='lower limb' %}
                                                                {{ 'mainpage.taglowerlimb'|trans }}
                                                            {% elseif tag=='Upper limb' %}
                                                                {{ 'mainpage.tagupperlimb'|trans }}
                                                            {% elseif tag=='neck & lower face' %}
                                                                {{ 'mainpage.tagnecklowerface'|trans }}
                                                            {% else %}
                                                                {{tag}}
                                                            {% endif %}
                                                        </span>
                                                </div>
                                            {% endif %}
                                                <div class="tab-content">
                                                    <!--            
                                                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                                                <tr>
                                                                {% for pid in projects[tag]|keys %}
                                                                        <td width="25%" height="150px" valign="top" style="vertical-align:top;">
                                                                            <div class="e_title">
                                                                                <h6>
                                                                                    {{projects[tag][pid].name}}

                                                                                    {% if not projects[tag][pid].free %} <span class="color-red">{{ 'mainpage.premium'|trans }}</span> {% else %} <span class="color-green" style='color:green'>{{ 'mainpage.free'|trans }}</span> {% endif %}
                                                                                </h6>
                                                                            </div>
                                                                            <a href="{{ path('swarminfo_imagescript_main', {}) }}?id={{projects[tag][pid].id}}">
                                                                                <img class="cast-shadow" alt="Screenshot" src="{{projects[tag][pid].url}}" width="85px">
                                                                            </a>
                                                                            {{projects[tag][pid].images}} Images</td>
                                                                    {% if (pid+1) is divisible by(4) %}
                                                                </tr>
                                                                <tr>
                                                                    {% endif %}
                                                                {% endfor %}
                                                                </tr>
                                                        </table>
													-->
													
													
													<div class="list-thumbZone">
														{% for pid in projects[tag]|keys  if projects[tag][pid].isshow  %}
															<div id="thumbZone" class="thumbZone">
																<div class="e_title">
																	<h6>
																		{{projects[tag][pid].name}}
																	</h6>
																</div>
																<a href="{{ path('swarminfo_imagescript_main', {}) }}?id={{projects[tag][pid].id}}&search={{ search|replace({' ': "_"}) }}">
																	<img class="cast-shadow" alt="Screenshot" src="{{projects[tag][pid].url}}">
																</a>
																<div class="thumbBottom">
																	<div>
																	{% if not projects[tag][pid].free %} <span class="color-red">{{ 'mainpage.premium'|trans }}</span> {% else %} <span class="color-green" style='color:green'>{{ 'mainpage.free'|trans }}</span> {% endif %}
																	</div>
																	<div>
																	{{projects[tag][pid].images}} Images
																	</div>
																</div>
															</div>
															{% if (pid+1) is divisible by(4) %}
																{% endif %}
															{% endfor %}
													</div>
													
                                                </div>
                                            {% if not search %}
                                                </li>
                                            {% endif %}

                                        {% endfor %}
                                    </ul>
                                            
                            </div>

                    </div>
            </div>

        <div class="row">
            <div class="container" >
                <div class="slide-right">
                    <div class="row ">
                        <div class="col-md-8">
                            {#<img class="cast-shadow" alt="Screenshot" src="{{ asset('bundles/swarminfoimagescript/img/body_image.jpg') }}">#}

                            <iframe id="skeleton" frameBorder="0" width="1170px" src=/frontpageiframe>
                                <!--<div id=imagescriptcontainer webkitAllowFullScreen mozAllowFullScreen allowFullScreen>
                                    <div class=scriptDiv id=topuserpannel></div>
                                    <div id=middle>
                                        <div id=lefttrackdown></div>
                                        <div id=rightblock>

                                            <div class=scriptDiv id=mainimage></div>
                                            <div class=scriptDiv id=bottomband></div>
                                            <div class=scriptDiv id=topadminpannel></div>
                                            <div class=scriptDiv id=mainadminpannel></div>
                                        </div>
                                    </div>
                                </div>-->
                            </iframe>
                        </div>
                        <div class="col-md-4 image-slider">
                            {% for tag in projects|keys %}
                                <div class="right_slide">
                                    {% for pid in projects[tag]|keys if  projects[tag][pid].onfront and projects[tag][pid].free  %}
                                            <div class="thumbZone_right">
                                                <div class="e_title">
                                                    <h8>
                                                        {{projects[tag][pid].name}}
                                                    </h8>
                                                </div>
                                                <a href="{{ path('swarminfo_imagescript_main', {}) }}?id={{projects[tag][pid].id}}">
                                                    <img class="cast-shadow_right" alt="Screenshot" src="{{projects[tag][pid].url}}">
                                                </a>

                                            </div>
                                        {% if (pid+1) is divisible by(4) %}
                                        {% endif %}
                                    {% endfor %}
                                </div>

                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
            
    </div>


</section>
        {% include 'SwarminfoImagescriptBundle::footer.html.twig' %}
    </div>

    <script>

    </script>

{% endblock %}